##
## strfry config for mdk-e2e-test integration tests
##

db = "./strfry-db/"

dbParams {
    maxreaders = 256
    mapsize = 10995116277760
    noReadAhead = false
}

events {
    maxEventSize = 131072
    rejectEventsNewerThanSeconds = 900
    rejectEventsOlderThanSeconds = 94608000
    rejectEphemeralEventsOlderThanSeconds = 60
    ephemeralEventsLifetimeSeconds = 300
    maxNumTags = 2000
    maxTagValSize = 4096
}

relay {
    bind = "0.0.0.0"
    port = 7777
    nofiles = 65536
    realIpHeader = ""

    info {
        name = "mdk-e2e-test"
        description = "strfry instance for MDK e2e tests"
        pubkey = ""
        contact = ""
        icon = ""
        nips = ""
    }

    maxWebsocketPayloadSize = 262144
    maxReqFilterSize = 200
    autoPingSeconds = 55
    enableTcpKeepalive = false
    queryTimesliceBudgetMicroseconds = 10000
    maxFilterLimit = 500
    maxSubsPerConnection = 20

    writePolicy {
        plugin = ""
    }

    compression {
        enabled = true
        slidingWindow = true
    }

    logging {
        dumpInAll = false
        dumpInEvents = false
        dumpInReqs = false
        dbScanPerf = false
        invalidEvents = true
    }

    numThreads {
        ingester = 3
        reqWorker = 3
        reqMonitor = 3
        negentropy = 2
    }

    negentropy {
        enabled = true
        maxSyncEvents = 1000000
    }
}
